# -*- coding: utf-8 -*-
"""Generate BI node curriculum JSON and validate."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(r"D:\cursor\数据学习平台\_gen\bi_node_curriculum.json")

DATA = {
    "bi_node": {
        "node_id": "BI",
        "title": "BI 工具",
        "description": "以 Tableau 为代表的可视化分析工具：从基础图表到 LOD、仪表板、建模与性能的完整学习树。",
        "children": [
            {
                "node_id": "BI.ChartBasics",
                "title": "图表基础",
                "description": "掌握最常用的四类基础图：柱状、折线、饼图、散点，能独立完成拖拽成图。",
                "difficulty": 1,
                "estimated_hours": 4,
                "prerequisites": [],
                "knowledge_points": [
                    {
                        "kp_id": "BI.ChartBasics.柱状图",
                        "title": "柱状图",
                        "difficulty": 1,
                        "description": "用柱子的高度表示数值大小，适合比较不同类别之间的数值差异。是 BI 入门的第一张「对比图」。",
                        "how_to_make": "1. 确认对比字段：类别维度（如 Region）与数值度量（如 Sales）。2. 将维度拖到「列」，度量拖到「行」。3. 标记卡选择「条形」。4. 按度量降序排序，必要时添加数据标签。5. 检查类别数量是否过多导致柱子过细。",
                        "use_cases": ["各区域销售额对比", "月度订单量对比", "品类利润对比"],
                        "common_mistakes": ["类别过多导致柱子太细难读", "用柱状图硬画长时间连续趋势（更适合折线）", "未排序导致重点不突出"],
                        "practice": "用 Superstore 数据做「各区域销售额」柱状图，并按 Sales 降序排序。",
                        "prerequisites": [],
                    },
                    {
                        "kp_id": "BI.ChartBasics.折线图",
                        "title": "折线图",
                        "difficulty": 1,
                        "description": "用线条连接数据点，展示度量随时间（或有序轴）的变化趋势。适合看涨跌与拐点。",
                        "how_to_make": "1. 准备日期字段与度量（如 Order Date、Sales）。2. 将日期拖到「列」并设为连续日期（如月）。3. 将度量拖到「行」。4. 标记卡选择「线」，需要时可打开标记标签。5. 核对横轴连续性与空值断点是否合理。",
                        "use_cases": ["月度销售趋势", "同比/环比走势", "多系列产品线趋势对比"],
                        "common_mistakes": ["把日期当成离散分类导致断线杂乱", "系列过多导致「意面图」", "纵轴从非 0 起步造成误导"],
                        "practice": "用 Superstore 做「月度销售额」折线图，并叠加「利润」第二系列（可不双轴，先同轴观察）。",
                        "prerequisites": ["BI.ChartBasics.柱状图"],
                    },
                    {
                        "kp_id": "BI.ChartBasics.饼图",
                        "title": "饼图",
                        "difficulty": 1,
                        "description": "用扇形面积（角度）表示占比，适合展示「部分占总体」的结构。切片不宜过多。",
                        "how_to_make": "1. 准备分类维度与占比度量。2. 标记卡选择「饼图」。3. 将维度放到「颜色」，度量放到「角度」。4. 按角度降序排列切片，必要时加百分比标签。5. 验证切片数是否 ≤5，过多则改条形占比或合并「其他」。",
                        "use_cases": ["各区域销售占比", "支付方式结构", "流量来源占比"],
                        "common_mistakes": ["切片超过 5~7 个导致难读", "用饼图比较微小差异", "忽略从 12 点方向顺时针、最大块优先的排序习惯"],
                        "practice": "用 Superstore 做「各区域销售占比」饼图，切片按销售额从大到小排列，并标注百分比。",
                        "prerequisites": ["BI.ChartBasics.柱状图"],
                    },
                    {
                        "kp_id": "BI.ChartBasics.散点图",
                        "title": "散点图",
                        "difficulty": 2,
                        "description": "用点在二维坐标中的位置展示两个度量之间的关系（相关、聚类、异常点）。",
                        "how_to_make": "1. 选定两个度量（如 Sales、Profit）和一个可选维度。2. 将度量1拖到「列」，度量2拖到「行」。3. 标记卡选择「圆」。4. 可选：颜色放维度、大小放第三个度量。5. 观察趋势方向、离群点与是否需要聚合/去重粒度。",
                        "use_cases": ["销售额与利润相关性", "客户价值分布", "异常订单识别"],
                        "common_mistakes": ["粒度过细导致点糊成一团", "两轴量纲差异巨大未调整", "把相关当成因果"],
                        "practice": "用 Superstore 在客户粒度做 Sales vs Profit 散点图，用 Category 上色，圈出亏损异常点。",
                        "prerequisites": ["BI.ChartBasics.柱状图", "BI.ChartBasics.折线图"],
                    },
                    {
                        "kp_id": "BI.ChartBasics.维度与标记卡",
                        "title": "维度、度量与标记卡",
                        "difficulty": 1,
                        "description": "理解拖拽式分析的核心：维度切片、度量聚合；标记卡控制颜色/大小/标签/详细信息。",
                        "how_to_make": "1. 在数据窗格区分蓝色维度与绿色度量。2. 将字段拖到行/列构建骨架。3. 打开标记卡，按图表需要放置颜色、大小、标签。4. 用「详细信息」控制粒度而不改变视觉编码。5. 用汇总/聚合切换验证结果是否符合预期。",
                        "use_cases": ["快速切换图表类型", "同一指标多重视觉编码", "控制视图粒度"],
                        "common_mistakes": ["误把度量当维度导致拆分爆炸", "在详细信息里塞过多字段拖垮性能", "不懂聚合粒度导致重复计算"],
                        "practice": "同一张柱状图上，分别用颜色、标签、详细信息放置 Region，观察视图变化差异。",
                        "prerequisites": [],
                    },
                    {
                        "kp_id": "BI.ChartBasics.筛选与排序",
                        "title": "筛选、排序与快速表计算入门",
                        "difficulty": 2,
                        "description": "学会用筛选器缩小范围、用排序突出重点，并初识占比/排名等快速表计算。",
                        "how_to_make": "1. 将维度/度量拖到筛选器并设置条件。2. 对轴或表头设置升/降序。3. 右键度量 → 快速表计算（如总额百分比、排名）。4. 确认计算依据（表/窗格）正确。5. 用筛选前后对比验证数字。",
                        "use_cases": ["TopN 产品", "区域筛选后的趋势", "占比与排名看板"],
                        "common_mistakes": ["筛选器位置导致 LOD/表计算结果误解", "排名计算依据选错", "隐藏筛选却未说明口径"],
                        "practice": "在区域销售额柱状图上加 Category 筛选，并做「占总额百分比」标签。",
                        "prerequisites": ["BI.ChartBasics.柱状图", "BI.ChartBasics.维度与标记卡"],
                    },
                ],
            },
            {
                "node_id": "BI.AdvancedCharts",
                "title": "图表进阶",
                "description": "掌握复合与特殊图表：环形图、双轴组合、热力、桑基，解决「一张图讲清两件事」。",
                "difficulty": 3,
                "estimated_hours": 6,
                "prerequisites": ["BI.ChartBasics"],
                "knowledge_points": [
                    {
                        "kp_id": "BI.AdvancedCharts.环形图",
                        "title": "环形图",
                        "difficulty": 3,
                        "description": "中间镂空的饼图，视觉更轻量，中心可放 KPI 数字。由双轴叠两个饼/圆实现。",
                        "how_to_make": "1. 先按饼图做法：标记选饼图，颜色放维度，角度放度量。2. 将「记录数」拖入行两次（或复制饼度量），均改为最小值聚合，形成两个饼层。3. 右键第二个轴选择「双轴」，并同步轴范围使两饼同心。4. 在内圈标记卡删除颜色与角度，缩小尺寸，颜色设为白色（或画布底色）遮盖中心。5. 外圈保留标签，检查切片排序与占比合计为 100%。",
                        "use_cases": ["品类销售占比（现代风格）", "中心显示总 GMV 的结构图", "仪表板主视觉占比卡"],
                        "common_mistakes": ["未同步轴导致不同心", "内圈未去角度仍显示扇区", "切片过多失去环形图优势"],
                        "practice": "用 Superstore 做「品类销售额」标准环形图，中心标注总销售额。",
                        "prerequisites": ["BI.ChartBasics.饼图"],
                    },
                    {
                        "kp_id": "BI.AdvancedCharts.双轴组合图",
                        "title": "双轴组合图（柱状+折线）",
                        "difficulty": 3,
                        "description": "同一视图用两种标记展示两个度量，例如柱表示销售额、线表示利润率。",
                        "how_to_make": "1. 将连续日期拖到「列」。2. 将销售额拖到「行」，再将利润（或利润率）拖到「行」。3. 右键第二个度量选择「双轴」。4. 左侧标记卡改为「条形」，右侧标记卡改为「线」；量纲相近时右键轴「同步轴」。5. 检查图例、轴标题与是否需要偏移日期避免柱子重叠。",
                        "use_cases": ["月度销售额（柱）+ 利润率（线）", "订单量 + 客单价", "曝光量 + 转化率"],
                        "common_mistakes": ["两度量量纲差巨大却强行同步轴", "双柱默认堆叠/重叠未处理", "忘记区分左右标记卡"],
                        "practice": "制作「月度销售额柱 + 利润率线」双轴图，轴不同步，并写清左右轴单位。",
                        "prerequisites": ["BI.ChartBasics.柱状图", "BI.ChartBasics.折线图"],
                    },
                    {
                        "kp_id": "BI.AdvancedCharts.热力图",
                        "title": "热力图",
                        "difficulty": 2,
                        "description": "用颜色深浅在二维交叉表上编码数值强度，适合看密度、高峰时段与交叉组合强弱。",
                        "how_to_make": "1. 选定行维度与列维度（如 Weekday × Hour 或 Region × Category）。2. 将行维度放「行」、列维度放「列」。3. 将度量放「颜色」，标记选「方形」。4. 调整色阶（顺序色/发散色）与空值显示。5. 必要时加标签或限色域，避免极端值洗白色阶。",
                        "use_cases": ["星期×小时订单热力", "区域×品类销售强度", "相关性矩阵可视化"],
                        "common_mistakes": ["色盲不友好配色", "极值导致色阶失真", "维度交叉过密无法阅读"],
                        "practice": "用 Superstore 做 Region × Category 的 Sales 热力图，并标出最深三格。",
                        "prerequisites": ["BI.ChartBasics.维度与标记卡"],
                    },
                    {
                        "kp_id": "BI.AdvancedCharts.桑基图",
                        "title": "桑基图",
                        "difficulty": 4,
                        "description": "用流向宽度表示流量或金额在阶段之间的转移，适合漏斗多路径与流转分析。",
                        "how_to_make": "1. 准备「起点-终点-数值」三列（或阶段对）。2. 确认工具路径：Tableau 扩展插件 / 数据 densify 计算字段方案。3. 按文档配置源节点、目标节点与流量度量。4. 调整节点顺序与颜色映射业务阶段。5. 用抽样流量验证宽窄是否与合计一致。",
                        "use_cases": ["流量渠道→落地页流转", "订单状态迁移", "预算在部门间分配"],
                        "common_mistakes": ["源数据不是边列表导致无法绘制", "节点过多导致「毛线团」", "把桑基当普通漏斗硬套"],
                        "practice": "整理一份「Region → Category」销售流向边表，尝试用扩展或示意草图完成桑基。",
                        "prerequisites": ["BI.ChartBasics.维度与标记卡", "BI.AdvancedCharts.热力图"],
                    },
                    {
                        "kp_id": "BI.AdvancedCharts.双轴避坑",
                        "title": "双轴常见坑与图层",
                        "difficulty": 3,
                        "description": "双轴图易出现柱体重叠、轴误导、图层前后错乱；需掌握同步轴、偏移与移动标记前后。",
                        "how_to_make": "1. 复现问题：两度量同为条形时的重叠。2. 对日期用 CASE WHEN 做微小偏移，或改一侧为线。3. 右键轴决定是否同步；不同步时必须标注单位。4. 用「移动标记到前/后」管理图层。5. 用筛选器测试双轴是否仍联动正确。",
                        "use_cases": ["柱线组合调优", "仪表板主图稳定性", "双度量对比规范"],
                        "common_mistakes": ["用双轴制造虚假相关", "图层遮挡关键标签", "筛选后双轴不同步刷新"],
                        "practice": "故意做一张双柱重叠图，再用「线+柱」或日期偏移修复，截图前后对比。",
                        "prerequisites": ["BI.AdvancedCharts.双轴组合图"],
                    },
                    {
                        "kp_id": "BI.AdvancedCharts.多标记卡",
                        "title": "多标记卡架构",
                        "difficulty": 4,
                        "description": "每个度量/双轴层对应一张标记卡，相当于一层透明画布；复合图的本质是多层标记叠加。",
                        "how_to_make": "1. 放入两个度量形成多标记卡。2. 分别设置每层的标记类型、颜色、大小。3. 用双轴或共享轴决定空间关系。4. 检查图例是否按层拆分清晰。5. 在仪表板中测试筛选联动是否作用到所有层。",
                        "use_cases": ["复杂组合图", "参考线+主系列", "多层 KPI 装饰"],
                        "common_mistakes": ["改错标记卡导致「怎么改都不动」", "层数过多难维护", "颜色编码冲突"],
                        "practice": "在双轴图上为柱层与线层设置不同颜色与标签策略，并写出每层职责。",
                        "prerequisites": ["BI.AdvancedCharts.双轴组合图"],
                    },
                ],
            },
            {
                "node_id": "BI.LOD",
                "title": "LOD 表达式",
                "description": "Level of Detail：在视图粒度之外按指定维度做聚合，是中高级 Tableau 的核心能力。",
                "difficulty": 4,
                "estimated_hours": 8,
                "prerequisites": ["BI.ChartBasics", "BI.DataModeling"],
                "knowledge_points": [
                    {
                        "kp_id": "BI.LOD.是什么",
                        "title": "LOD 是什么",
                        "difficulty": 3,
                        "description": "LOD（Level of Detail）用于控制计算发生的粒度层级。当「视图里的聚合粒度」不等于「你想要的聚合粒度」时，就需要 LOD：不必把维度拖进视图，也能按指定维度计算。",
                        "how_to_make": "1. 先说清视图当前粒度（行上有哪些维度）。2. 写出「我想要的粒度」一句话。3. 若两者不一致，再选择 FIXED/INCLUDE/EXCLUDE。4. 创建计算字段并用简单视图验证。5. 对照筛选器与表计算结果，确认语义。",
                        "use_cases": ["明细行旁展示客户终身价值", "占比分母锁定", "队列/首次购买日分析"],
                        "common_mistakes": ["视图粒度本已满足却滥用 LOD", "不会先口述粒度差异", "把 LOD 当成普通聚合函数乱用"],
                        "practice": "打开一张「订单明细」视图，口述：视图粒度是什么；若要显示「客户总销售额」粒度差在哪。",
                        "prerequisites": ["BI.ChartBasics.维度与标记卡", "BI.DataModeling.维度vs度量"],
                    },
                    {
                        "kp_id": "BI.LOD.FIXED",
                        "title": "FIXED",
                        "difficulty": 4,
                        "description": "忽略视图中的其他维度，固定到声明的维度上计算聚合。语法：{ FIXED [维度] : 聚合([度量]) }。典型用于「每个客户的总销售额」「各区域总额」等不随视图切片漂移的指标。注意：通常忽略普通维度筛选器，主要受上下文筛选器影响。",
                        "how_to_make": "1. 分析菜单 → 创建计算字段。2. 输入如 { FIXED [Customer Name] : SUM([Sales]) }。3. 将结果拖到视图（标签/提示/列）。4. 用不同维度切片视图，确认该值不随无关维度变化。5. 再分别用普通筛选器与上下文筛选器测试差异。",
                        "use_cases": ["每个客户的总销售额展示在订单行", "各区域总销售额作占比分母", "客户首次下单日（阵列分析）"],
                        "common_mistakes": ["以为 FIXED 一定受所有筛选器影响", "固定维度选错导致「全表一个数」", "在小问题场景滥用 FIXED 伤性能"],
                        "practice": "用 FIXED 计算每个客户总销售额，在订单明细表中显示；再算各州占所属区域总额的占比。",
                        "prerequisites": ["BI.LOD.是什么"],
                    },
                    {
                        "kp_id": "BI.LOD.INCLUDE",
                        "title": "INCLUDE",
                        "difficulty": 4,
                        "description": "在当前视图维度基础上，额外加入声明维度再聚合。语法：{ INCLUDE [维度] : 聚合([度量]) }。适合「视图较粗，但想先按更细粒度算再回聚」的场景。",
                        "how_to_make": "1. 确认视图已有较粗维度（如 Category）。2. 创建 { INCLUDE [Sub-Category] : SUM([Sales]) } 等计算。3. 外层再对结果做 AVG 等聚合（按业务）。4. 对比「直接按 Category 聚合」与「先 Sub-Category 再平均」的差异。5. 记录业务口径说明。",
                        "use_cases": ["类别视图下按子类别算平均销售", "先按天再按月的特殊均值", "细粒度评分上卷"],
                        "common_mistakes": ["忘了外层还要再聚合", "与 FIXED 场景混淆", "细维度基数不稳导致均值被稀疏值扭曲"],
                        "practice": "视图只有 Category：比较 SUM(Sales) 与 AVG({ INCLUDE [Sub-Category] : SUM([Sales]) }) 的差异并解释。",
                        "prerequisites": ["BI.LOD.是什么", "BI.LOD.FIXED"],
                    },
                    {
                        "kp_id": "BI.LOD.EXCLUDE",
                        "title": "EXCLUDE",
                        "difficulty": 4,
                        "description": "从当前视图维度中排除声明维度后再聚合。语法：{ EXCLUDE [维度] : 聚合([度量]) }。适合「视图很细，但想拿更粗层级的总额做对比/占比」。",
                        "how_to_make": "1. 视图放入 Category + Sub-Category。2. 创建 { EXCLUDE [Sub-Category] : SUM([Sales]) } 得到类别层总额。3. 用 SUM([Sales]) / 该 LOD 得到子类别占类别比。4. 切换筛选验证语义。5. 与 FIXED([Category]: SUM(Sales)) 对照理解等价/不等价条件。",
                        "use_cases": ["子类别占所属类别比重", "明细行旁显示上级汇总", "去掉某维后的对照基准"],
                        "common_mistakes": ["排除维度后仍期望结果随该维变化", "与表计算「按窗格总计」混用不清", "筛选器语义未验证"],
                        "practice": "在 Category×Sub-Category 视图中，用 EXCLUDE 做子类别占类别百分比，并与表计算占比对照。",
                        "prerequisites": ["BI.LOD.是什么", "BI.LOD.FIXED"],
                    },
                    {
                        "kp_id": "BI.LOD.执行顺序",
                        "title": "LOD 执行顺序",
                        "difficulty": 4,
                        "description": "LOD 在 Tableau 查询管道中通常晚于数据源/上下文筛选相关步骤，但整体上 LOD 结果会先于表计算参与后续可视化计算。理解顺序才能解释「筛选器为何不起作用」与性能成本。",
                        "how_to_make": "1. 画一张简图：上下文筛选 → LOD → 维度筛选 → 表计算（示意，便于记忆）。2. 用同一 FIXED 字段分别挂普通筛选与上下文筛选做实验。3. 再对同一视图加表计算排名，观察谁先谁后。4. 记录实验结论到笔记。5. 对照官方 Order of Operations 文档纠偏。",
                        "use_cases": ["解释筛选器异常", "设计上下文筛选", "排查占比分母被筛掉"],
                        "common_mistakes": ["死记硬背却不做对照实验", "把所有筛选问题都甩给 LOD", "忽略提取/关系模型对管道的影响"],
                        "practice": "设计 3 组对照：普通筛选、上下文筛选、表计算，记录 FIXED 结果是否变化。",
                        "prerequisites": ["BI.LOD.FIXED", "BI.LOD.INCLUDE", "BI.LOD.EXCLUDE"],
                    },
                    {
                        "kp_id": "BI.LOD.常见坑",
                        "title": "LOD 常见坑",
                        "difficulty": 4,
                        "description": "三大坑：与筛选器交互不符合直觉；与表计算优先级混淆；FIXED 过多触发额外查询导致仪表板变慢。",
                        "how_to_make": "1. 列出仪表板中所有 LOD 字段及用途。2. 逐个检查是否可用表计算/普通聚合替代。3. 对必须保留的 FIXED，评估是否改为 INCLUDE/EXCLUDE 或预聚合。4. 用性能记录确认查询次数。5. 形成「LOD 使用规范」三条军规。",
                        "use_cases": ["慢仪表板治理", "口径争议仲裁", "新人 Code Review"],
                        "common_mistakes": ["堆砌 FIXED 当万金油", "用 LOD 复制已有摘要表", "不写口径注释"],
                        "practice": "找一个含 ≥2 个 FIXED 的练习簿，删掉可替代的一个，证明结果不变且更快。",
                        "prerequisites": ["BI.LOD.执行顺序", "BI.Performance.LOD性能"],
                    },
                    {
                        "kp_id": "BI.LOD.实战客户总额",
                        "title": "实战：客户总额与区域占比",
                        "difficulty": 4,
                        "description": "用 FIXED 在明细视图展示客户总销售额，并用区域 FIXED 总额计算州占比，巩固「分母锁定」思维。",
                        "how_to_make": "1. 创建 Customer Sales = { FIXED [Customer Name] : SUM([Sales]) }。2. 在订单明细表中显示该字段。3. 创建 Region Sales = { FIXED [Region] : SUM([Sales]) }。4. 州占比 = SUM([Sales]) / SUM([Region Sales])（注意聚合）。5. 用区域筛选验证分母是否按预期锁定或变化。",
                        "use_cases": ["客户价值分析", "区域结构占比", "筛选器敏感口径设计"],
                        "common_mistakes": ["占比未聚合报错", "分母被筛选掏空", "客户名重复未清洗"],
                        "practice": "完成客户总额列 + 州占区域比两张工作表，并写入口径说明文本框。",
                        "prerequisites": ["BI.LOD.FIXED", "BI.LOD.执行顺序"],
                    },
                    {
                        "kp_id": "BI.LOD.阵列与行级",
                        "title": "行级别 LOD 与阵列分析",
                        "difficulty": 5,
                        "description": "行级别写法如 { SUM([Sales]) } 可返回全局总额；用 { FIXED [Customer ID] : MIN([Order Date]) } 可做首次购买日，进而做 Cohort 阵列分析。",
                        "how_to_make": "1. 创建全局总额或行级 LOD 理解省略维度的含义。2. 创建首次购买日 FIXED。3. 计算订单日与首次日的月份差作为队列年龄。4. 做成队列热力/表。5. 检查新客定义与时区/空单边界。",
                        "use_cases": ["Cohort 留存", "新客首单分析", "全局 KPI 分母"],
                        "common_mistakes": ["首单定义含取消单", "队列年龄计算 off-by-one", "全局 LOD 滥用导致常数列过重"],
                        "practice": "用 Superstore 计算客户首次购买月，并做简单队列人数表。",
                        "prerequisites": ["BI.LOD.FIXED", "BI.AdvancedCharts.热力图"],
                    },
                ],
            },
            {
                "node_id": "BI.DashboardDesign",
                "title": "仪表板设计",
                "description": "把多张工作表编排成可决策的仪表板：布局、信息层级、交互、移动端与配色规范。",
                "difficulty": 3,
                "estimated_hours": 5,
                "prerequisites": ["BI.ChartBasics", "BI.AdvancedCharts"],
                "knowledge_points": [
                    {
                        "kp_id": "BI.DashboardDesign.布局原则",
                        "title": "布局原则",
                        "difficulty": 2,
                        "description": "仪表板是「一屏讲清一个决策问题」。遵循对齐、留白、分区与视觉权重，避免卡片堆砌。",
                        "how_to_make": "1. 写清仪表板唯一目标用户与决策问题。2. 画线框：上 KPI、中主图、下明细。3. 用容器（水平/垂直）固定结构。4. 统一边距与对齐。5. 删除不能服务决策的装饰图。",
                        "use_cases": ["经营日报", "销售复盘看板", "运营监控屏"],
                        "common_mistakes": ["一屏塞十个无关图", "无留白、无对齐", "装饰重于信息"],
                        "practice": "为「销售复盘」画一页线框，只保留 3 个主视觉区域。",
                        "prerequisites": [],
                    },
                    {
                        "kp_id": "BI.DashboardDesign.信息层级",
                        "title": "信息层级",
                        "difficulty": 3,
                        "description": "先结论后证据：KPI → 趋势/结构 → 明细下钻。视觉动线符合 F/Z 型阅读习惯。",
                        "how_to_make": "1. 列出必须一眼看到的 3 个 KPI。2. 主图回答「为什么」。3. 次图回答「哪里/谁」。4. 明细表支持核对。5. 用字号/颜色权重区分层级，不靠闪烁。",
                        "use_cases": ["管理层一页纸", "周会材料", "异常定位"],
                        "common_mistakes": ["明细表当主视觉", "同权重色块打架", "没有默认筛选导致首屏空白"],
                        "practice": "把已有练习簿重排为 KPI→趋势→结构→明细四层，并请同事 5 秒说出结论。",
                        "prerequisites": ["BI.DashboardDesign.布局原则"],
                    },
                    {
                        "kp_id": "BI.DashboardDesign.交互设计",
                        "title": "交互设计（筛选器、参数、动作）",
                        "difficulty": 3,
                        "description": "用筛选器联动、参数与仪表板动作（高亮/筛选/URL）让用户自助探索，同时防止误操作。",
                        "how_to_make": "1. 放置关键维度筛选器并设默认值。2. 配置工作表间「用作筛选器」或动作。3. 对 What-if 场景引入参数。4. 限制筛选器数量（宁可分层）。5. 测试清空筛选与交叉筛选的边界。",
                        "use_cases": ["点击区域过滤明细", "参数切换度量", "下钻到订单行"],
                        "common_mistakes": ["筛选器过多造成选择瘫痪", "动作冲突互相覆盖", "移动端手势难用的控件"],
                        "practice": "做销售复盘仪表板：区域饼图点击筛选趋势折线与 TopN 条形图。",
                        "prerequisites": ["BI.DashboardDesign.信息层级", "BI.ChartBasics.筛选与排序"],
                    },
                    {
                        "kp_id": "BI.DashboardDesign.移动端适配",
                        "title": "移动端适配",
                        "difficulty": 3,
                        "description": "为手机/平板单独设计设备布局：更大触控、更少图表、纵向信息流。",
                        "how_to_make": "1. 仪表板 → 设备布局 → 手机。2. 改为单列堆叠。3. 放大筛选控件与 KPI。4. 隐藏次要图表。5. 真机或模拟器检查滚动与点击。",
                        "use_cases": ["外勤查看业绩", "管理层手机催数", "简易预警卡"],
                        "common_mistakes": ["直接缩小桌面版", "双轴图在窄屏难读", "筛选器挡住主图"],
                        "practice": "为同一仪表板新增手机布局，保证首屏可见 3 个 KPI + 1 张主图。",
                        "prerequisites": ["BI.DashboardDesign.布局原则"],
                    },
                    {
                        "kp_id": "BI.DashboardDesign.配色规范",
                        "title": "配色规范",
                        "difficulty": 2,
                        "description": "配色服务语义：顺序色表大小、发散色表正负、分类色表类别；保持全仪表板一致并考虑色盲友好。",
                        "how_to_make": "1. 定义品牌主色与中性灰。2. 为 KPI 涨跌规定红绿（或蓝橙）语义。3. 分类色不超过 6~8 个。4. 热力选用感知均匀色阶。5. 导出色板说明写入团队规范。",
                        "use_cases": ["企业视觉统一", "正负利润表达", "多仪表板一致性"],
                        "common_mistakes": ["彩虹色过多", "红绿唯一依赖", "每张图一套色"],
                        "practice": "制定一页配色规范，并应用到柱状、热力、KPI 三类组件。",
                        "prerequisites": ["BI.DashboardDesign.布局原则"],
                    },
                ],
            },
            {
                "node_id": "BI.DataModeling",
                "title": "数据建模",
                "description": "为分析准备正确的数据形态：维度度量、关系与连接、数据源治理、提取与实时。",
                "difficulty": 3,
                "estimated_hours": 5,
                "prerequisites": [],
                "knowledge_points": [
                    {
                        "kp_id": "BI.DataModeling.维度vs度量",
                        "title": "维度 vs 度量",
                        "difficulty": 1,
                        "description": "维度用于切片与分组（通常离散/蓝色），度量用于聚合计算（通常连续/绿色）。建错类型会导致图表与 LOD 全部跑偏。",
                        "how_to_make": "1. 检查每个字段默认角色。2. 将 ID、编码等误判字段改为维度。3. 将可加总业务指标保持为度量。4. 为度量设置默认聚合与数字格式。5. 用一张简单柱状图验证。",
                        "use_cases": ["字段角色纠正", "防止求和 ID", "统一默认聚合"],
                        "common_mistakes": ["对 Order ID 求和", "把日期当普通字符串", "度量默认聚合选错"],
                        "practice": "打开 Superstore，列出 5 个易混字段并纠正角色/默认聚合。",
                        "prerequisites": [],
                    },
                    {
                        "kp_id": "BI.DataModeling.关系vs连接",
                        "title": "关系 vs 连接",
                        "difficulty": 3,
                        "description": "关系（Relationship）在逻辑层按需合并，减少过早行膨胀；传统连接（Join）在物理层先拼表。现代 Tableau 优先关系，必要时再用连接/自定义 SQL。",
                        "how_to_make": "1. 在数据源页拖入多表。2. 配置关系键与基数/参照完整性（若可知）。3. 需要强制行级拼表时再使用连接。4. 用行数与指标对比检查爆炸。5. 记录模型图供团队复用。",
                        "use_cases": ["事实表关联维表", "多事实分析", "避免 JOIN 爆炸"],
                        "common_mistakes": ["多对多乱连导致指标放大", "该用关系却用连接", "忽略空匹配"],
                        "practice": "用 Orders 与 Returns 比较关系与左连接在退货率上的差异。",
                        "prerequisites": ["BI.DataModeling.维度vs度量"],
                    },
                    {
                        "kp_id": "BI.DataModeling.数据源管理",
                        "title": "数据源管理",
                        "difficulty": 2,
                        "description": "统一发布、命名、认证与刷新策略，避免每人私有副本造成口径分裂。",
                        "how_to_make": "1. 约定数据源命名与文件夹。2. 发布到 Server/Cloud 并设权限。3. 标记认证数据源。4. 文档化刷新时间与 Owner。5. 废弃旧副本并通知下游。",
                        "use_cases": ["团队协作", "口径治理", "权限最小化"],
                        "common_mistakes": ["本地文件满天飞", "同名不同源", "无 Owner 无人刷新"],
                        "practice": "写一份「Superstore 练习源」发布检查单（命名/权限/刷新/认证）。",
                        "prerequisites": ["BI.DataModeling.维度vs度量"],
                    },
                    {
                        "kp_id": "BI.DataModeling.提取vs实时",
                        "title": "提取 vs 实时连接",
                        "difficulty": 2,
                        "description": "提取（Extract）提升性能与稳定性，适合绝大多数分析；实时连接保证最新，但受源库性能与网络制约。",
                        "how_to_make": "1. 评估时效要求与源库压力。2. 默认创建提取并增量刷新。3. 仅对强时效指标用实时或混合。4. 隐藏不用字段、过滤历史降体积。5. 监控失败刷新告警。",
                        "use_cases": ["日报看板提取", "实时库存监控", "混合数据源"],
                        "common_mistakes": ["全家实时拖垮源库", "提取过大不做裁剪", "刷新失败无人知"],
                        "practice": "同一仪表板分别用提取与实时对比打开耗时，并写下选型结论。",
                        "prerequisites": ["BI.DataModeling.数据源管理"],
                    },
                    {
                        "kp_id": "BI.DataModeling.粒度与多表",
                        "title": "分析粒度与多表陷阱",
                        "difficulty": 3,
                        "description": "分析前先定义「一行代表什么」。多表关联时，错误粒度会让 SUM 翻倍，表现像「图表会骗人」。",
                        "how_to_make": "1. 为每张表写清业务粒度。2. 关联后检查行数变化。3. 对一对多场景用适当聚合或 LOD。4. 在可视化前用表视图抽样。5. 把粒度写进数据源说明。",
                        "use_cases": ["订单头+明细", "退货关联", "营销触达匹配"],
                        "common_mistakes": ["明细关联后对头金额直接 SUM", "忽略一对多", "不抽样就做仪表板"],
                        "practice": "关联 Orders 与 Order Details（或等价表），演示错误 SUM 与正确聚合的对比。",
                        "prerequisites": ["BI.DataModeling.关系vs连接"],
                    },
                ],
            },
            {
                "node_id": "BI.Performance",
                "title": "性能优化",
                "description": "让仪表板又快又稳：提取裁剪、计算下推、LOD 收敛、加载路径优化。",
                "difficulty": 4,
                "estimated_hours": 4,
                "prerequisites": ["BI.DataModeling", "BI.LOD", "BI.DashboardDesign"],
                "knowledge_points": [
                    {
                        "kp_id": "BI.Performance.提取优化",
                        "title": "提取优化",
                        "difficulty": 3,
                        "description": "通过隐藏字段、过滤历史、聚合提取、增量刷新，显著减小提取体积并加快查询。",
                        "how_to_make": "1. 隐藏未用字段。2. 提取过滤只保留近 N 年。3. 能聚合提取则聚合。4. 配置增量键与刷新日程。5. 对比提取前后体积与打开时间。",
                        "use_cases": ["大体量业务表", "日报稳定刷新", "移动端加速"],
                        "common_mistakes": ["全量历史无过滤", "增量键选错漏数", "隐藏字段后工作簿仍引用"],
                        "practice": "将练习提取裁剪到近 2 年并隐藏 10 个未用字段，记录体积变化。",
                        "prerequisites": ["BI.DataModeling.提取vs实时"],
                    },
                    {
                        "kp_id": "BI.Performance.计算优化",
                        "title": "计算字段优化",
                        "difficulty": 3,
                        "description": "优先用原生聚合与简单计算；避免行级复杂字符串/正则；能下推到数据库/ETL 的不要放在视图。",
                        "how_to_make": "1. 列出最慢计算字段。2. 能改为提取内物化则物化。3. 用 ATTR/简单 IF 替代嵌套。4. 减少对大文本字段的即时处理。5. 用性能记录验证。",
                        "use_cases": ["复杂 IF 链治理", "字符串解析外移", "指标预计算"],
                        "common_mistakes": ["视图里做重变换", "重复计算同一逻辑多份", "忽略数字类型转换成本"],
                        "practice": "把一个复杂计算改写为更简单版本或预计算列，对比耗时。",
                        "prerequisites": ["BI.DataModeling.维度vs度量"],
                    },
                    {
                        "kp_id": "BI.Performance.LOD性能",
                        "title": "LOD 性能影响",
                        "difficulty": 4,
                        "description": "FIXED 等 LOD 可能触发额外子查询；在大数据集上叠加多个 FIXED 会明显拖慢仪表板。能表计算解决的不要上 FIXED。",
                        "how_to_make": "1. 统计工作簿 LOD 数量与类型。2. 标记仅用于展示且可用表计算替代者。3. 合并可共用的 FIXED 维度集。4. 对超慢 LOD 改为上游汇总表。5. 回归业务结果后发布。",
                        "use_cases": ["慢看板急救", "LOD 规范制定", "大数据集分析"],
                        "common_mistakes": ["每个 KPI 一个 FIXED", "在明细百万行上堆 LOD", "优化后不回归口径"],
                        "practice": "构造含 3 个 FIXED 的慢表，删到 1 个并保持核心结论不变。",
                        "prerequisites": ["BI.LOD.FIXED", "BI.LOD.常见坑"],
                    },
                    {
                        "kp_id": "BI.Performance.仪表板加载",
                        "title": "仪表板加载优化",
                        "difficulty": 3,
                        "description": "减少工作表数、固定尺寸、避免过高分辨率图片、延迟加载明细、限制筛选器选项基数。",
                        "how_to_make": "1. 用性能记录看首屏瓶颈。2. 合并重复工作表。3. 明细表改为点击后显示。4. 筛选器改相关值/通配。5. 控制设备布局资源。",
                        "use_cases": ["首屏 3 秒目标", "大屏投放", "并发早高峰"],
                        "common_mistakes": ["一仪表板二十张表", "高清底图当背景", "筛选器加载全部基数"],
                        "practice": "把一张「又慢又杂」的仪表板减到 ≤6 个可见对象，并记录加载时间。",
                        "prerequisites": ["BI.DashboardDesign.布局原则", "BI.Performance.提取优化"],
                    },
                    {
                        "kp_id": "BI.Performance.监控与规范",
                        "title": "性能监控与团队规范",
                        "difficulty": 3,
                        "description": "建立可重复的优化清单与发布门槛：性能记录、LOD 数量上限、提取大小上限、认证源强制。",
                        "how_to_make": "1. 起草一页性能规范。2. 定义发布前自检表。3. 抽样审计现有仪表板。4. 对超标对象建改进 backlog。5. 复盘一次优化案例沉淀模板。",
                        "use_cases": ["团队治理", "上线门槛", "新人培训"],
                        "common_mistakes": ["只有口号没有门槛", "不测量就优化", "规范不更新"],
                        "practice": "输出《BI 性能发布检查单》至少 8 条，并在一份工作簿上试跑。",
                        "prerequisites": ["BI.Performance.仪表板加载", "BI.Performance.LOD性能"],
                    },
                ],
            },
        ],
    }
}


def main():
    # counts
    children = DATA["bi_node"]["children"]
    assert len(children) == 6
    for ch in children:
        n = len(ch["knowledge_points"])
        assert 3 <= n <= 8, ch["node_id"]
        for kp in ch["knowledge_points"]:
            assert "how_to_make" in kp and kp["how_to_make"].strip()

    # required charts
    titles = {
        kp["title"]
        for ch in children
        for kp in ch["knowledge_points"]
    }
    for t in ["柱状图", "折线图", "饼图", "散点图", "环形图", "双轴组合图（柱状+折线）", "热力图", "桑基图", "FIXED", "INCLUDE", "EXCLUDE", "LOD 是什么"]:
        assert t in titles, t

    text = json.dumps(DATA, ensure_ascii=False, indent=2)
    # round-trip
    json.loads(text)
    OUT.write_text(text + "\n", encoding="utf-8")
    print("OK", OUT)
    for ch in children:
        print(ch["node_id"], len(ch["knowledge_points"]))


if __name__ == "__main__":
    main()
