-- 由 portfolio/scripts/export_etl_lineage_sql.py 生成 · 勿手改
USE portfolio_metadata;
DELETE FROM etl_transform_edge;
DELETE FROM etl_schedule_job;

INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('retail', 'dim_date', 'dim_date 初始化', '重建时', 'sql6_portfolio_model/02_dim.sql · 2020–2030');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('retail', 'csv_ods', 'CSV → ODS', '按需', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('retail', 'ods_dwd', 'ODS → DWD 宽表', '灌入后', 'JOIN dim_* 冗余品牌/渠道/品类/门店名称');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('retail', 'dwd_dws', 'DWD → DWS 汇总', '灌入后', '日/月 × 品牌 × 渠道 × 品类预聚合；支付/预算见 07_dws_payment_budget_etl.sql');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('retail', 'ads_views', 'ADS 视图', '实时', 'sql6_portfolio_model/05_ads.sql 仅读 DWS/DIM');

INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_csv_ods_orders', 'CSV/ERP', 'ods_orders', 'ODS', 'ODS', 'CSV → ODS', '按需', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_ods_orders', '从作品集 CSV 解析订单行，写入贴源 ods_orders（金额 DECIMAL、业务键 order_id）。', 'INSERT INTO ods_orders (order_id, order_date, order_amount, ...)', '订单行');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_ods_dwd_sales', 'ods_orders', 'dwd_sales_wide', 'ODS', 'DWD', 'ODS → DWD 宽表', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dwd_sales_wide', '订单 JOIN dim_brand/channel/category/store，冗余中文维名；清洗退款与异常金额。', 'INSERT INTO dwd_sales_wide SELECT o.*, b.brand_name, c.channel_name ... FROM ods_orders o JOIN dim_*', '销售明细宽表');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_ods_dwd_exp', 'ods_expense', 'dwd_expense_wide', 'ODS', 'DWD', 'ODS → DWD 宽表', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dwd_expense_wide', '费用报销与广告投放合并进费用宽表，冗余品牌/渠道。', 'INSERT INTO dwd_expense_wide ... UNION 广告费口径', '费用明细');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_ods_dwd_inv', 'ods_inventory', 'dwd_inventory_wide', 'ODS', 'DWD', 'ODS → DWD 宽表', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dwd_inventory_wide', '库存变动净额按品类/门店展开为库存宽表。', 'INSERT INTO dwd_inventory_wide SELECT ...', '库存明细');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_dwd_dws_daily', 'dwd_sales_wide', 'dws_sales_daily', 'DWD', 'DWS', 'DWD → DWS 汇总', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dws_sales_daily', '按日×品牌×渠道×品类 SUM(销售额/成本/订单数)。', 'GROUP BY order_date, brand_name, channel_name, category_name', '日×品牌×渠道×品类');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_dwd_dws_monthly', 'dwd_sales_wide', 'dws_sales_monthly', 'DWD', 'DWS', 'DWD → DWS 汇总', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dws_sales_monthly', '按月预聚合销售核心指标，供经营总览与杜邦。', 'GROUP BY DATE_FORMAT(order_date,''%Y-%m''), brand, channel, category', '月×品牌×渠道×品类');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_dwd_dws_exp', 'dwd_expense_wide', 'dws_expense_monthly', 'DWD', 'DWS', 'DWD → DWS 汇总', '灌入后', 'python', 'retail-finance-analysis/scripts/seed_sql6_from_csv.py', 'load_dws_expense_monthly', '费用月汇总，支撑费用结构与预算对比。', 'SUM(expense_amount) GROUP BY month, brand, channel', '月×品牌×渠道');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_pay_dws', 'ods_payment', 'dws_payment_monthly', 'ODS', 'DWS', 'DWD → DWS 汇总', '灌入后', 'sql', 'retail-finance-analysis/sql6_portfolio_model/07_dws_payment_budget_etl.sql', 'dws_payment_monthly', '支付按月×品牌×渠道×支付方式汇总实收。', 'INSERT INTO dws_payment_monthly SELECT month, brand, channel, method, SUM(pay_amount)', '月×品牌×渠道×支付方式');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_budget_dws', 'ods_budget', 'dws_budget_monthly', 'ODS', 'DWS', 'DWD → DWS 汇总', '灌入后', 'sql', 'retail-finance-analysis/sql6_portfolio_model/07_dws_payment_budget_etl.sql', 'dws_budget_monthly', '预算 vs 实际费用：差异额与达成率。', 'budget_amount - actual_amount AS variance; achievement_pct', '月×科目');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_dws_ads_overview', 'dws_sales_monthly', 'v_overview', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'retail-finance-analysis/sql6_portfolio_model/05_ads.sql', 'v_overview', '经营总览 ADS：消费 DWS 月销售/费用等预聚合，禁止直读 ODS。', 'CREATE OR REPLACE VIEW v_overview AS SELECT ... FROM dws_sales_monthly', '看板切片');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('retail', 'rtl_dws_ads_brand', 'dws_sales_daily', 'v_brand_analysis', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'retail-finance-analysis/sql6_portfolio_model/05_ads.sql', '品牌分析相关视图', '品牌主题看板读 DWS 日/月销售汇总。', 'SELECT brand_name, SUM(revenue) FROM dws_sales_*', '品牌切片');

INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('manufacturing', 'ddl_dim', 'DDL / DIM', '重建时', 'database/01_ods.sql … 05_ads.sql 建表与维度');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('manufacturing', 'seed_sample', '样例灌入', '按需', 'cd database && python seed_manufacturing_data.py（含增强 seed_enhance.py）');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('manufacturing', 'ods_dwd_dws', 'ODS → DWD → DWS', '灌入后 / T+1', 'seed 链式装载宽表与日/月汇总；补充 06_migrate_dws_ads.sql');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('manufacturing', 'ads_views', 'ADS 视图', '实时', '05_ads.sql 仅读 DWS/DIM；看板只消费 ADS/DWS');

INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_po_dwd', 'ods_production_order', 'dwd_production_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dwd_production_wide', '工单贴源 JOIN dim_production_line / dim_product，冗余产线名/产品名；按计划与实际产量派生材料/人工/制造费用代理成本。', 'INSERT INTO dwd_production_wide SELECT o.*, l.line_name, p.product_name, ... FROM ods_production_order o LEFT JOIN dim_*', '工单级明细');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_qi_dwd', 'ods_quality_inspection', 'dwd_quality_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dwd_quality_wide', '质检单 JOIN 产线/产品维；良品率 = pass_qty / NULLIF(total_qty,0) * 100。', 'yield_rate = pass_qty / NULLIF(total_qty,0) * 100', '质检单级');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_inv_dwd', 'ods_inventory_material', 'dwd_supply_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dwd_supply_wide', '库存快照 JOIN dim_material / dim_supplier，形成供应事实宽表（日×物料×供应商粒度）。', 'INSERT INTO dwd_supply_wide SELECT i.*, m.material_name, s.supplier_name ...', '日×物料×供应商');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_labor_dwd', 'ods_labor', 'dwd_labor_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/manufacturing/database/seed_enhance.py', 'load_dwd_labor_wide', '工时明细 JOIN 产线与工单，冗余工厂/产品维度，供人效与成本下钻。', 'INSERT INTO dwd_labor_wide SELECT l.*, line.factory_code, o.product_code ...', '工时记录级');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_eq_dwd', 'ods_equipment', 'dwd_equipment_run', 'ODS', 'DWD', '样例灌入', '按需', 'python', 'portfolio/industries/manufacturing/database/seed_enhance.py', 'expand_equipment_run', '由日 OEE/设备台账展开为班次运行事实（计划/运行/停机分钟）。', 'INSERT INTO dwd_equipment_run SELECT equipment_code, shift, planned_min, run_min, downtime_min ...', '设备×日×班次');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dwd_prod_dws', 'dwd_production_wide', 'dws_production_daily', 'DWD', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_production_daily', '按日×厂×线汇总产量/计划；产能利用率与准时交付率按产量加权，禁止对百分比做简单 AVG。', 'SUM(output_qty); capacity_util = SUM(util*qty)/SUM(qty)', '日×工厂×产线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dwd_qi_dws', 'dwd_quality_wide', 'dws_quality_daily', 'DWD', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_quality_daily', '日×线×产品汇总检验量/合格/不良/报废；良品率与 FPY 按检验量加权。', 'yield_rate_pct = SUM(pass)/SUM(total)*100', '日×产线×产品');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dwd_sup_dws', 'dwd_supply_wide', 'dws_supply_daily', 'DWD', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_supply_daily', '供应日汇总：采购额、库存周转天数、供应商 OTD；金额类作权重。', 'GROUP BY snapshot_date, material_code, supplier_code', '日×物料×供应商');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_labor_dws', 'ods_labor', 'dws_labor_monthly', 'ODS', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_labor_monthly', '按月×工厂×产线 SUM(plan_hours/actual_hours/labor_cost)；工时达成率 = actual/plan*100；同步见 06_migrate_dws_ads.sql。', 'INSERT INTO dws_labor_monthly SELECT DATE_FORMAT(work_date,''%Y-%m''), factory_code, line_code, SUM(...)', '月×工厂×产线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_labor_dws_sql', 'ods_labor', 'dws_labor_monthly', 'ODS', 'DWS', 'ODS → DWD → DWS', '迁移补数', 'sql', 'portfolio/industries/manufacturing/database/06_migrate_dws_ads.sql', 'DELETE/INSERT dws_labor_monthly', 'SQL 迁移脚本：从 ods_labor 重算月人工效率快照，与 Python seed 口径对齐。', 'INSERT INTO dws_labor_monthly SELECT DATE_FORMAT(work_date,''%Y-%m''), ... FROM ods_labor GROUP BY 1,2,3', '月×工厂×产线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_inv_mat_dws', 'ods_inventory_material', 'dws_material_daily', 'ODS', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_material_daily', '周转天数 = on_hand_qty / NULLIF(daily_usage,0)；库存金额 = qty × standard_price。', 'turnover_days = on_hand_qty / NULLIF(daily_usage,0)', '日×物料');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_qi_defect_dws', 'ods_quality_inspection', 'dws_defect_daily', 'ODS', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_defect_daily', '按日×缺陷类型×产线汇总不良/报废；不良率 = defect/total*100。', 'GROUP BY snapshot_date, defect_type, line_code', '日×缺陷类型×产线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_ods_eq_dws', 'ods_equipment', 'dws_equipment_daily', 'ODS', 'DWS', 'ODS → DWD → DWS', '灌入后 / T+1', 'python', 'portfolio/industries/manufacturing/database/seed_manufacturing_data.py', 'load_dws_equipment_daily', '设备日 OEE = 可用率×性能率×质量率；汇总停机小时与故障次数。', 'oee_pct = availability * performance * quality / 10000', '日×设备');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_prod_ads', 'dws_production_daily', 'v_production_overview', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_production_overview', '排除 ALL 汇总行后按日加权产能利用率与准时交付率，供生产总览看板。', 'SELECT snapshot_date, SUM(output_qty), SUM(util*qty)/SUM(qty) FROM dws_production_daily WHERE line_code<>''ALL''', '日汇总切片');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_labor_ads', 'dws_labor_monthly', 'v_labor_efficiency', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_labor_efficiency', 'ADS 只读投影月人工效率快照（计划/实际工时、达成率、人工成本），禁止回读 ODS。', 'CREATE OR REPLACE VIEW v_labor_efficiency AS SELECT * FROM dws_labor_monthly 列投影', '月×工厂×产线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_mat_ads', 'dws_material_daily', 'v_material_turnover', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_material_turnover', '物料周转看板直接消费 DWS 日物料周转指标。', 'SELECT snapshot_date, material_code, turnover_days, on_hand_amount FROM dws_material_daily', '日×物料');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_def_ads', 'dws_defect_daily', 'v_defect_analysis', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_defect_analysis', '不良分析看板读 DWS 缺陷日汇总，做柏拉图与结构分析。', 'SELECT * FROM dws_defect_daily', '日×缺陷类型');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_qi_ads', 'dws_quality_daily', 'v_quality_analysis', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_quality_analysis', '按日加权良品率/不良率/一次通过率。', 'SUM(pass)/SUM(total)*100 AS yield_rate_pct', '日汇总');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dws_eq_ads', 'dws_equipment_daily', 'v_equipment_oee', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/manufacturing/database/05_ads.sql', 'CREATE VIEW v_equipment_oee', '设备 OEE 看板直读 DWS 日指标。', 'SELECT snapshot_date, equipment_code, oee_pct, downtime_hours FROM dws_equipment_daily', '日×设备');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('manufacturing', 'mfg_dwd_fact_prod', 'dwd_production_wide', 'fact_production', 'DWD', 'DWD', 'DDL / DIM', '重建时', 'view', 'portfolio/industries/manufacturing/database/07_fact_aliases.sql', 'CREATE VIEW fact_production', '跨行业命名同义视图：fact_production = SELECT * FROM dwd_production_wide。', 'CREATE OR REPLACE VIEW fact_production AS SELECT * FROM dwd_production_wide', '同 DWD 工单粒度');

INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('internet', 'dim_init', '维度初始化', '重建时', 'database/01_ddl.sql · dim_* / ods_*');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('internet', 'seed_ods', '样例灌入 ODS', '按需', 'python seed_internet_data.py / seed_ott.py');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('internet', 'ods_dwd_dws', 'ODS → DWD → DWS', '灌入后', 'seed 内 SQL INSERT 宽表与日/月汇总');
INSERT INTO etl_schedule_job (industry, job_id, job_name, schedule, description) VALUES ('internet', 'ads_views', 'ADS 视图', '实时', '02_ads.sql / 04_ott_ads_views.sql 仅读 DWS/DWD');

INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_ods_op_dwd', 'ods_device_operation_log', 'dwd_device_operation_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dwd_device_operation_wide', '开机/点播/直播操作日志 JOIN 设备与用户维，形成行为宽表。', 'INSERT INTO dwd_device_operation_wide SELECT log.*, device.*, user.* ...', '一次设备行为');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_ods_user_dwd', 'ods_user_profile', 'dwd_user_wide', 'ODS', 'DWD', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dwd_user_wide', '用户档案宽表；再 UPDATE last_active / is_paid（来自行为与订购）。', 'INSERT INTO dwd_user_wide ...; UPDATE ... JOIN dwd_device_operation_wide', '用户');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_dwd_op_session', 'dwd_device_operation_wide', 'dwd_session_wide', 'DWD', 'DWD', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dwd_session_wide', '按 session_id 汇总行为次数与时长。', 'INSERT INTO dwd_session_wide SELECT session_id, user_id, COUNT(*), SUM(duration) ... GROUP BY session_id', '会话');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_ods_sub_dws', 'ods_subscription_order', 'dws_payment_daily', 'ODS', 'DWS', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dws_payment_daily', '订购按支付日×渠道×产品线汇总付费用户/金额/ARPU。', 'GROUP BY pay_date, channel_code, product_line; arpu = pay_amount/pay_users', '日×渠道×产品线');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_dwd_funnel', 'dwd_device_operation_wide', 'dws_funnel_monthly', 'DWD', 'DWS', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dws_funnel_monthly', '按月统计漏斗各步人数（曝光→点击→转化）。', 'INSERT INTO dws_funnel_monthly SELECT month, step, COUNT(DISTINCT user_id)', '月×漏斗步骤');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_dwd_value', 'dwd_user_wide', 'dws_user_value_snapshot', 'DWD', 'DWS', 'ODS → DWD → DWS', '灌入后', 'python', 'portfolio/industries/internet/database/seed_internet_data.py', 'build_dws_user_value_snapshot', '用户价值快照：生命周期阶段、付费标记、活跃分。', 'INSERT INTO dws_user_value_snapshot SELECT user_id, lifecycle_stage, is_paid ...', '用户快照');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_dws_ads_dau', 'dws_user_daily', 'v_dau_overview', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/internet/database/02_ads.sql', 'v_dau_overview', '日活总览视图，消费 DWS 用户日活跃汇总。', 'CREATE OR REPLACE VIEW v_dau_overview AS SELECT ... FROM dws_user_daily', '日活切片');
INSERT INTO etl_transform_edge (industry, edge_id, from_table, to_table, layer_from, layer_to, job_name, schedule, engine, code_path, entry_point, computation, sql_excerpt, grain) VALUES ('internet', 'inet_dws_ads_pay', 'dws_payment_daily', 'v_revenue_structure', 'DWS', 'ADS', 'ADS 视图', '实时', 'view', 'portfolio/industries/internet/database/04_ott_ads_views.sql', '收入结构相关视图', '收入结构看板读支付日汇总，按渠道/产品线切分。', 'SELECT channel_code, product_line, SUM(pay_amount) FROM dws_payment_daily', '收入切片');

